// Code generated by goctl. DO NOT EDIT.
package types

type CreateOrderReq struct {
	TotalPrice float64         `json:"total_price"`
	OrderInfo  CreateOrderInfo `json:"order_info"`
}

type CreateOrderInfo struct {
	Client               int64              `json:"client"`
	AppointmentStartTime string             `json:"appointment_start_time"`
	AppointmentEndTime   string             `json:"appointment_end_time"`
	SenderAddressId      int64              `json:"sender_address_id"`
	ReceiveAddressId     int64              `json:"receive_address_id"`
	Remark               string             `json:"remark"`
	Goods                []CreateOrderGoods `json:"goods"`
}

type CreateOrderGoods struct {
	GoodsId   int64  `json:"goods_id"`
	Num       int64  `json:"num"`
	GoodsName string `json:"goods_name"`
}

type CreateOrderResp struct {
	Id                int64  `json:"id"`
	OrderSerialNumber string `json:"order_serial_number"`
}

type OrderItemReq struct {
	Id int64 `path:"id"`
}

type OrderItemResp struct {
	Id                int64  `json:"id"`
	OrderSerialNumber string `json:"order_serial_number"`
}

type OrdersCollectionReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type OrdersCollectionResp struct {
	Id                int64  `json:"id"`
	OrderSerialNumber string `json:"order_serial_number"`
	OrderStatus       string `json:"order_status"`
	OrderAmount       string `json:"order_amount"`
	GoodsNum          string `json:"goods_num"`
	PaymentLimitTime  string `json:"payment_limit_time"`
}
