// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "order/cmd/api/internal/handler/order"
	"order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: order.GetOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/:id",
				Handler: order.GetOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Jwt.AccessSecret),
		rest.WithPrefix("/order"),
	)
}
