// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameOrderGoods = "greet_order_goods"

// OrderGoods mapped from table <greet_order_goods>
type OrderGoods struct {
	ID           int64                 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	OrderID      int64                 `gorm:"column:order_id;type:int;not null" json:"order_id"`                              // 订单id
	CategoryID   int64                 `gorm:"column:category_id;type:int;not null" json:"category_id"`                        // 商品分类id
	CategoryName string                `gorm:"column:category_name;type:varchar(10);not null" json:"category_name"`            // 分类名称
	GoodsID      int64                 `gorm:"column:goods_id;type:int;not null" json:"goods_id"`                              // 商品id
	GoodsName    string                `gorm:"column:goods_name;type:varchar(50);not null" json:"goods_name"`                  // 商品名称
	GoodsPicture string                `gorm:"column:goods_picture;type:varchar(200);not null" json:"goods_picture"`           // 商品图片
	GoodsPrice   float64               `gorm:"column:goods_price;type:decimal(10,2);not null;default:0.00" json:"goods_price"` // 商品价格
	GoodsNum     int64                 `gorm:"column:goods_num;type:smallint;not null" json:"goods_num"`                       // 商品数量
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;type:timestamp;default:null" json:"deleted_at"`
	CreatedAt    *time.Time            `gorm:"column:created_at;type:timestamp;autoCreateTime" json:"created_at"`
	UpdatedAt    *time.Time            `gorm:"column:updated_at;type:timestamp;autoUpdateTime" json:"updated_at"`
}

// TableName OrderGoods's table name
func (*OrderGoods) TableName() string {
	return TableNameOrderGoods
}
