// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameCategory = "greet_category"

// Category mapped from table <greet_category>
type Category struct {
	ID              int64                 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CategoryID      int64                 `gorm:"column:category_id;type:int;not null" json:"category_id"`                          // 第三方Id
	CategoryPid     int64                 `gorm:"column:category_pid;type:int;not null" json:"category_pid"`                        // 第三方父级Id
	CategoryName    string                `gorm:"column:category_name;type:varchar(10);not null" json:"category_name"`              // 分类名称
	CategoryPicture string                `gorm:"column:category_picture;type:varchar(200);not null" json:"category_picture"`       // 分类图片
	DiffHash        string                `gorm:"column:diff_hash;type:varchar(32);not null" json:"diff_hash"`                      // 值hash
	IsRecommend     int64                 `gorm:"column:is_recommend;type:tinyint(1);not null" json:"is_recommend"`                 // 是否推荐1:已推荐;0:未推荐;
	CategoryStatus  int64                 `gorm:"column:category_status;type:tinyint(1);not null;default:1" json:"category_status"` // 分类状态1：使用；0：禁用；
	OperationUser   int64                 `gorm:"column:operation_user;type:int;not null" json:"operation_user"`                    // 操作人id
	DeletedAt       soft_delete.DeletedAt `gorm:"column:deleted_at;type:timestamp;default:null" json:"deleted_at"`
	CreatedAt       *time.Time            `gorm:"column:created_at;type:timestamp;autoCreateTime" json:"created_at"`
	UpdatedAt       *time.Time            `gorm:"column:updated_at;type:timestamp;autoUpdateTime" json:"updated_at"`
	GoodsSort       *int64                `gorm:"column:goods_sort;type:int" json:"goods_sort"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
