// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameOrderPayment = "greet_order_payment"

// OrderPayment mapped from table <greet_order_payment>
type OrderPayment struct {
	ID            int64                 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	OrderID       int64                 `gorm:"column:order_id;type:int;not null" json:"order_id"`                   // 订单id|补款单id
	MemberID      int64                 `gorm:"column:member_id;type:int;not null" json:"member_id"`                 // 用户id
	BusinessType  string                `gorm:"column:business_type;type:varchar(20);not null" json:"business_type"` // 业务类型
	OrderSn       string                `gorm:"column:order_sn;type:varchar(30);not null" json:"order_sn"`           // 销巴订单号|补款单号，未加索引，不能做条件字句
	PaymentStatus int64                 `gorm:"column:payment_status;type:smallint;not null" json:"payment_status"`  // 支付单状态1：已创建待支付；2：已支付；3：支付失败；4:支付异常,需要人工介入;
	PaymentSn     string                `gorm:"column:payment_sn;type:varchar(32);not null" json:"payment_sn"`       // 支付订单号（调用支付服务创建支付时返回）
	PaymentAmount *float64              `gorm:"column:payment_amount;type:decimal(10,2)" json:"payment_amount"`      // 支付单支付金额
	PaymentType   int64                 `gorm:"column:payment_type;type:tinyint;not null" json:"payment_type"`       // 支付方式： 1：银联支付 2：支付宝支付 3：微信支付 4.个人余额 5.小巴余额
	PaymentParams *string               `gorm:"column:payment_params;type:json" json:"payment_params"`               // 创建支付订单时的入参
	PaymentResult *string               `gorm:"column:payment_result;type:json" json:"payment_result"`               // 创建支付订单时的响应
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;type:timestamp;default:null" json:"deleted_at"`
	CreatedAt     *time.Time            `gorm:"column:created_at;type:timestamp;autoCreateTime" json:"created_at"`
	UpdatedAt     *time.Time            `gorm:"column:updated_at;type:timestamp;autoUpdateTime" json:"updated_at"`
}

// TableName OrderPayment's table name
func (*OrderPayment) TableName() string {
	return TableNameOrderPayment
}
