// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameAddress = "greet_address"

// Address mapped from table <greet_address>
type Address struct {
	ID              int64                 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	MemberID        int64                 `gorm:"column:member_id;type:int;not null" json:"member_id"`                        // 用户id
	ContactName     string                `gorm:"column:contact_name;type:varchar(10);not null" json:"contact_name"`          // 联系人姓名
	ContactMobile   string                `gorm:"column:contact_mobile;type:char(11);not null" json:"contact_mobile"`         // 联系人手机号
	ProvinceCode    string                `gorm:"column:province_code;type:varchar(6);not null" json:"province_code"`         // 地区编码 省
	CityCode        string                `gorm:"column:city_code;type:varchar(6);not null" json:"city_code"`                 // 地区编码 市
	CountyCode      string                `gorm:"column:county_code;type:varchar(6);not null" json:"county_code"`             // 地区编码 县
	ProvinceName    string                `gorm:"column:province_name;type:varchar(20);not null" json:"province_name"`        // 地区名称 省
	CityName        string                `gorm:"column:city_name;type:varchar(20);not null" json:"city_name"`                // 地区名称 市
	CountyName      string                `gorm:"column:county_name;type:varchar(20);not null" json:"county_name"`            // 地区名称 县
	DetailedAddress string                `gorm:"column:detailed_address;type:varchar(100);not null" json:"detailed_address"` // 详细地址
	FirstBoot       int64                 `gorm:"column:first_boot;type:tinyint(1);not null" json:"first_boot"`               // 默认地址1：是；0：否；
	DeletedAt       soft_delete.DeletedAt `gorm:"column:deleted_at;type:timestamp;default:null" json:"deleted_at"`
	CreatedAt       *time.Time            `gorm:"column:created_at;type:timestamp;autoCreateTime" json:"created_at"`
	UpdatedAt       *time.Time            `gorm:"column:updated_at;type:timestamp;autoUpdateTime" json:"updated_at"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
